<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Exercise;
use App\Models\Tag;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $categories = collect(['Yoga', 'Free Body', 'Strength', 'Cardio'])
            ->mapWithKeys(fn (string $name) => [
                $name => Category::firstOrCreate(
                    ['slug' => Str::slug($name)],
                    ['name' => $name],
                ),
            ]);

        $tags = collect([
            'knee', 'lower back', 'posture', 'flexibility', 'mobility', 'core', 'balance',
            'chest', 'arms', 'glutes', 'hip', 'quads', 'hamstrings', 'calves', 'ankle',
            'shoulder', 'back', 'grip', 'full body', 'cardio', 'coordination', 'power',
            'agility', 'speed', 'plyometric', 'endurance', 'abs',
        ])
            ->mapWithKeys(fn (string $name) => [
                $name => Tag::firstOrCreate(
                    ['slug' => Str::slug($name)],
                    ['name' => $name],
                ),
            ]);

        $exercises = [
            // Free Body
            ['Seated Knee Extension', 'Sit upright, extend one leg slowly until straight, hold, then lower.', 'Free Body', ['knee', 'mobility']],
            ['Plank Hold', 'Hold a straight line from head to heels on forearms and toes, bracing the core.', 'Free Body', ['core', 'posture']],
            ['Glute Bridge', 'Lie on your back, knees bent, and lift hips until shoulders, hips and knees align.', 'Free Body', ['lower back', 'core']],
            ['Push-Up', 'Lower your chest to the floor from a plank position, keeping the body straight, then press back up.', 'Free Body', ['chest', 'arms']],
            ['Diamond Push-Up', 'Perform a push-up with hands close together forming a diamond shape to target the triceps.', 'Free Body', ['arms', 'chest']],
            ['Wide Push-Up', 'Perform a push-up with hands set wider than shoulder-width to emphasize the chest.', 'Free Body', ['chest', 'arms']],
            ['Decline Push-Up', 'Elevate your feet on a bench and perform a push-up to target the upper chest.', 'Free Body', ['chest', 'shoulder']],
            ['Incline Push-Up', 'Place your hands on an elevated surface and perform a push-up to reduce load on the upper body.', 'Free Body', ['chest', 'arms']],
            ['Pike Push-Up', 'From a downward dog position, bend the elbows to lower the head toward the floor.', 'Free Body', ['shoulder', 'arms']],
            ['Burpee', 'Drop into a push-up, jump feet forward, then explode upward into a jump.', 'Free Body', ['full body', 'cardio']],
            ['Mountain Climber', 'From a plank, drive your knees alternately toward your chest at a quick pace.', 'Free Body', ['core', 'cardio']],
            ['Bicycle Crunch', 'Lie on your back and alternate bringing opposite elbow to knee in a pedaling motion.', 'Free Body', ['abs', 'core']],
            ['Russian Twist', 'Sit with knees bent and lean back slightly, rotating your torso side to side.', 'Free Body', ['abs', 'core']],
            ['Superman Hold', 'Lie face down and lift arms and legs simultaneously, holding the extended position.', 'Free Body', ['lower back', 'posture']],
            ['Bird Dog', 'From all fours, extend opposite arm and leg while keeping the spine neutral.', 'Free Body', ['core', 'balance']],
            ['Dead Bug', 'Lie on your back and lower opposite arm and leg toward the floor while bracing the core.', 'Free Body', ['core', 'coordination']],
            ['Hollow Body Hold', 'Lie on your back and lift shoulders and legs off the floor, pressing the lower back down.', 'Free Body', ['core', 'abs']],
            ['Side Plank', 'Balance on one forearm and the side of one foot, keeping hips lifted in a straight line.', 'Free Body', ['core', 'balance']],
            ['Reverse Plank', 'Sit with legs extended and lift your hips, supporting your weight on hands and heels.', 'Free Body', ['core', 'shoulder']],
            ['Bear Crawl', 'Move on hands and feet with knees hovering off the ground, alternating opposite limbs.', 'Free Body', ['core', 'coordination']],
            ['Crab Walk', 'Sit with hands behind you and hips lifted, walking forward on hands and feet.', 'Free Body', ['arms', 'core']],
            ['Wall Sit', 'Slide your back down a wall until knees are at ninety degrees and hold the position.', 'Free Body', ['quads', 'endurance']],
            ['Air Squat', 'Stand with feet shoulder-width and lower hips back and down until thighs are parallel, then rise.', 'Free Body', ['quads', 'glutes']],
            ['Jump Squat', 'Perform a squat and explode upward into a jump, landing softly back into the squat.', 'Free Body', ['quads', 'power']],
            ['Pistol Squat', 'Balance on one leg and lower into a full squat while extending the other leg forward.', 'Free Body', ['balance', 'quads']],
            ['Bulgarian Split Squat', 'Rest the back foot on a bench and lower into a lunge on the front leg.', 'Free Body', ['quads', 'glutes']],
            ['Lunge', 'Step forward and lower the back knee toward the floor, then push back to standing.', 'Free Body', ['quads', 'glutes']],
            ['Reverse Lunge', 'Step backward and lower the back knee toward the floor, then return to standing.', 'Free Body', ['quads', 'glutes']],
            ['Walking Lunge', 'Step forward into a lunge and continue alternating legs while moving forward.', 'Free Body', ['quads', 'endurance']],
            ['Curtsy Lunge', 'Step one leg diagonally behind the other and lower into a lunge, targeting the outer hip.', 'Free Body', ['glutes', 'hip']],
            ['Step-Up', 'Step onto a raised platform with one leg and drive through the heel to stand tall.', 'Free Body', ['quads', 'glutes']],
            ['Calf Raise', 'Rise onto the balls of your feet, pause, then lower slowly back down.', 'Free Body', ['calves', 'ankle']],
            ['Single-Leg Calf Raise', 'Balance on one foot and rise onto the ball of that foot, then lower with control.', 'Free Body', ['calves', 'balance']],
            ['Tricep Dip', 'Support your body on your hands behind you and lower by bending the elbows, then press up.', 'Free Body', ['arms', 'shoulder']],
            ['Chair Dip', 'Using a chair for support, lower your body by bending the elbows and press back up.', 'Free Body', ['arms', 'shoulder']],
            ['Inverted Row', 'Hang under a bar and pull your chest up toward it, keeping the body straight.', 'Free Body', ['back', 'arms']],
            ['Pull-Up', 'Hang from a bar and pull your chin above it, then lower with control.', 'Free Body', ['back', 'grip']],
            ['Chin-Up', 'Hang from a bar with palms facing you and pull your chin above it.', 'Free Body', ['back', 'arms']],
            ['Australian Pull-Up', 'Hang under a low bar with feet on the floor and pull your chest toward it.', 'Free Body', ['back', 'core']],
            ['Flutter Kicks', 'Lie on your back and alternate small up-and-down kicks with straight legs.', 'Free Body', ['abs', 'core']],
            ['Leg Raise', 'Lie on your back and lift straight legs toward the ceiling, then lower without touching the floor.', 'Free Body', ['abs', 'core']],
            ['Hanging Leg Raise', 'Hang from a bar and lift straight legs toward your chest, then lower with control.', 'Free Body', ['abs', 'grip']],
            ['V-Up', 'Lie flat and simultaneously lift torso and legs to form a V shape, touching hands to feet.', 'Free Body', ['abs', 'core']],
            ['Toe Touch Crunch', 'Lie on your back with legs raised and reach hands toward your toes, lifting the shoulders.', 'Free Body', ['abs', 'core']],
            ['Scissor Kicks', 'Lie on your back and cross straight legs alternately in a scissoring motion.', 'Free Body', ['abs', 'core']],
            ['Donkey Kick', 'From all fours, drive one heel toward the ceiling while keeping the knee bent.', 'Free Body', ['glutes', 'hip']],
            ['Fire Hydrant', 'From all fours, lift one bent knee out to the side, keeping the hips square.', 'Free Body', ['glutes', 'hip']],
            ['Clamshell', 'Lie on your side with knees bent and open the top knee like a clamshell, keeping feet together.', 'Free Body', ['hip', 'glutes']],
            ['Wall Push-Up', 'Stand facing a wall and perform a push-up against it, ideal for beginners.', 'Free Body', ['chest', 'arms']],
            ['Handstand Hold', 'Kick up into a handstand against a wall and hold, keeping the core braced.', 'Free Body', ['shoulder', 'balance']],

            // Yoga
            ['Cat-Cow Stretch', 'On all fours, alternate arching and rounding your spine with the breath.', 'Yoga', ['lower back', 'flexibility', 'posture']],
            ['Downward Dog', 'From all fours, lift hips up and back into an inverted V, heels toward the floor.', 'Yoga', ['flexibility', 'posture', 'mobility']],
            ["Child's Pose", 'Kneel and fold forward, resting your forehead on the floor with arms extended, breathing deeply.', 'Yoga', ['flexibility', 'lower back']],
            ['Cobra Pose', 'Lie face down and press through your palms to lift your chest, keeping hips on the floor.', 'Yoga', ['flexibility', 'lower back']],
            ['Warrior I', 'From a lunge, square your hips forward and raise both arms overhead, sinking into the front knee.', 'Yoga', ['balance', 'mobility']],
            ['Warrior II', 'From a wide stance, bend the front knee and extend arms parallel to the floor, gazing over the front hand.', 'Yoga', ['balance', 'hip']],
            ['Warrior III', 'Balance on one leg while hinging forward, extending the other leg and arms in one straight line.', 'Yoga', ['balance', 'core']],
            ['Triangle Pose', 'From a wide stance, hinge at the hip and reach one hand toward the front shin, the other to the sky.', 'Yoga', ['flexibility', 'balance']],
            ['Tree Pose', 'Balance on one leg with the other foot resting on the inner thigh, hands at heart center.', 'Yoga', ['balance', 'ankle']],
            ['Mountain Pose', 'Stand tall with feet grounded, shoulders relaxed, and weight evenly distributed.', 'Yoga', ['posture', 'balance']],
            ['Chair Pose', 'Bend your knees and sit back as if into a chair, raising arms overhead while keeping chest lifted.', 'Yoga', ['quads', 'balance']],
            ['Bridge Pose', 'Lie on your back, feet flat, and lift hips while pressing through your shoulders.', 'Yoga', ['lower back', 'glutes']],
            ['Camel Pose', 'Kneel upright and arch back, reaching hands to your heels while opening the chest.', 'Yoga', ['flexibility', 'posture']],
            ['Pigeon Pose', 'From all fours, bring one knee forward and extend the other leg back, folding over the front shin.', 'Yoga', ['hip', 'flexibility']],
            ['Seated Forward Bend', 'Sit with legs extended and hinge forward from the hips, reaching toward your feet.', 'Yoga', ['flexibility', 'lower back']],
            ['Bound Angle Pose', 'Sit with soles of the feet together, knees dropping outward, and fold gently forward.', 'Yoga', ['hip', 'flexibility']],
            ['Corpse Pose', 'Lie flat on your back with arms relaxed at your sides, breathing slowly to release tension.', 'Yoga', ['flexibility', 'posture']],
            ['Extended Side Angle', 'From a lunge, tilt the torso over the front leg and extend the top arm overhead.', 'Yoga', ['flexibility', 'balance']],
            ['Half Moon Pose', 'Balance on one hand and one leg, extending the other leg and arm toward the ceiling.', 'Yoga', ['balance', 'core']],
            ['Eagle Pose', 'Wrap one leg and arm around the other while balancing on the standing leg.', 'Yoga', ['balance', 'coordination']],
            ['Crow Pose', 'Balance your knees on your upper arms and lift your feet off the floor, engaging the core.', 'Yoga', ['core', 'balance']],
            ['Locust Pose', 'Lie face down and lift chest, arms, and legs simultaneously, engaging the back muscles.', 'Yoga', ['lower back', 'posture']],
            ['Bow Pose', 'Lie face down, bend knees, and reach back to hold ankles, lifting chest and thighs.', 'Yoga', ['flexibility', 'lower back']],
            ['Fish Pose', 'Lie on your back and arch the upper spine, resting the crown of the head lightly on the floor.', 'Yoga', ['flexibility', 'posture']],
            ['Plow Pose', 'Lie on your back and lift legs overhead until toes touch the floor behind you.', 'Yoga', ['flexibility', 'lower back']],
            ['Shoulder Stand', 'Lie on your back and lift legs and hips vertically, supporting your lower back with your hands.', 'Yoga', ['shoulder', 'balance']],
            ['Headstand', 'Balance on your forearms and head, lifting legs straight up toward the ceiling.', 'Yoga', ['balance', 'core']],
            ['Sphinx Pose', 'Lie face down and prop up on your forearms, lifting the chest while keeping hips grounded.', 'Yoga', ['lower back', 'posture']],
            ['Reclining Twist', 'Lie on your back and drop both knees to one side while keeping shoulders flat.', 'Yoga', ['lower back', 'mobility']],
            ['Standing Forward Bend', 'From standing, hinge at the hips and fold forward, letting the head hang toward the floor.', 'Yoga', ['flexibility', 'hamstrings']],
            ['Wide-Legged Forward Bend', 'Stand with feet wide and fold forward, reaching hands toward the floor between your legs.', 'Yoga', ['flexibility', 'hamstrings']],
            ['Garland Pose', 'Squat deep with feet flat, palms together, elbows pressing knees outward.', 'Yoga', ['hip', 'mobility']],
            ['Lizard Pose', 'From a lunge, lower the back knee and walk the front foot outward, opening the hip.', 'Yoga', ['hip', 'flexibility']],
            ['Frog Pose', 'Kneel and widen the knees while keeping ankles in line with knees, sinking hips back.', 'Yoga', ['hip', 'flexibility']],
            ['Happy Baby Pose', 'Lie on your back and grab the outer edges of your feet, pulling knees toward the floor.', 'Yoga', ['hip', 'flexibility']],
            ['Legs Up the Wall', 'Lie on your back with legs extended vertically against a wall, arms relaxed at your sides.', 'Yoga', ['flexibility', 'lower back']],
            ['Thread the Needle', 'From all fours, slide one arm under the other and rest your shoulder on the floor.', 'Yoga', ['shoulder', 'mobility']],
            ['Puppy Pose', 'Kneel and walk your hands forward, lowering your chest toward the floor with hips lifted.', 'Yoga', ['flexibility', 'shoulder']],
            ['Gate Pose', 'Kneel with one leg extended to the side and reach overhead, leaning over the extended leg.', 'Yoga', ['flexibility', 'balance']],
            ['Revolved Triangle', 'From a wide stance, twist the torso and reach the opposite hand toward the front foot.', 'Yoga', ['mobility', 'balance']],
            ['Dolphin Pose', 'From forearms and toes, lift hips up and back into an inverted V shape.', 'Yoga', ['shoulder', 'flexibility']],
            ['Side Plank Pose', 'Balance on one hand and the outer edge of one foot, stacking hips and shoulders.', 'Yoga', ['core', 'balance']],
            ['Low Lunge', 'Step one foot forward into a deep lunge, lowering the back knee and lifting the chest.', 'Yoga', ['hip', 'flexibility']],
            ['High Lunge', 'Step one foot forward into a lunge, keeping the back leg straight and arms overhead.', 'Yoga', ['balance', 'hip']],
            ['Crescent Lunge Twist', 'From a high lunge, rotate the torso toward the front leg with hands at heart center.', 'Yoga', ['mobility', 'balance']],
            ['Standing Split', 'Hinge forward on one leg and lift the other straight up behind you.', 'Yoga', ['flexibility', 'balance']],
            ['Wind Relieving Pose', 'Lie on your back and hug one knee into the chest, keeping the other leg extended.', 'Yoga', ['lower back', 'hip']],
            ['Cow Face Pose', 'Sit and stack one knee over the other while reaching arms behind your back to clasp hands.', 'Yoga', ['shoulder', 'hip']],
            ['Rabbit Pose', 'Kneel and fold forward, rolling onto the crown of the head while holding your heels.', 'Yoga', ['flexibility', 'posture']],
            ['Supine Butterfly', 'Lie on your back with soles of the feet together, knees dropping open.', 'Yoga', ['hip', 'flexibility']],

            // Strength
            ['Barbell Back Squat', 'With the bar across your upper back, squat down keeping the chest up, then drive up.', 'Strength', ['core', 'balance']],
            ['Barbell Deadlift', 'Hinge at the hips to grip the bar, then drive through the heels to stand tall with the bar close to the body.', 'Strength', ['back', 'lower back']],
            ['Romanian Deadlift', 'Holding the bar, hinge at the hips while keeping legs mostly straight, then return to standing.', 'Strength', ['hamstrings', 'lower back']],
            ['Sumo Deadlift', 'With a wide stance and toes turned out, grip the bar inside your legs and drive up to standing.', 'Strength', ['glutes', 'hamstrings']],
            ['Front Squat', 'Rest the bar across your front shoulders and squat down keeping the torso upright, then stand.', 'Strength', ['quads', 'core']],
            ['Overhead Squat', 'Hold the bar overhead with locked arms and squat down while maintaining balance.', 'Strength', ['shoulder', 'balance']],
            ['Bench Press', 'Lie on a bench and lower the bar to your chest, then press it back up.', 'Strength', ['chest', 'arms']],
            ['Incline Bench Press', 'On an inclined bench, lower the bar to the upper chest, then press it back up.', 'Strength', ['chest', 'shoulder']],
            ['Decline Bench Press', 'On a declined bench, lower the bar to the lower chest, then press it back up.', 'Strength', ['chest', 'arms']],
            ['Dumbbell Bench Press', 'Lie on a bench and press dumbbells up from chest height until arms are extended.', 'Strength', ['chest', 'arms']],
            ['Overhead Press', 'Standing, press the bar from shoulder height straight overhead until arms lock out.', 'Strength', ['shoulder', 'arms']],
            ['Push Press', 'Dip the knees slightly and drive the bar overhead using leg momentum.', 'Strength', ['shoulder', 'power']],
            ['Arnold Press', 'Press dumbbells overhead while rotating the palms from facing you to facing forward.', 'Strength', ['shoulder', 'arms']],
            ['Barbell Row', 'Hinge forward and pull the bar toward your abdomen, squeezing the shoulder blades together.', 'Strength', ['back', 'arms']],
            ['Dumbbell Row', 'Support one hand on a bench and row a dumbbell toward your hip with the other arm.', 'Strength', ['back', 'arms']],
            ['Pendlay Row', 'From a bent-over position, explosively pull the bar from the floor to your abdomen.', 'Strength', ['back', 'power']],
            ['T-Bar Row', 'Straddle the bar and pull the loaded end up toward your chest, squeezing the back.', 'Strength', ['back', 'arms']],
            ['Lat Pulldown', 'Pull a bar down toward your chest from an overhead cable, then control it back up.', 'Strength', ['back', 'arms']],
            ['Seated Cable Row', 'Sit and pull the cable handle toward your torso, squeezing the shoulder blades together.', 'Strength', ['back', 'arms']],
            ['Barbell Curl', 'Hold the bar with an underhand grip and curl it toward your shoulders, then lower.', 'Strength', ['arms', 'grip']],
            ['Dumbbell Curl', 'Curl a dumbbell in each hand toward your shoulders, then lower with control.', 'Strength', ['arms', 'grip']],
            ['Hammer Curl', 'Curl dumbbells with palms facing each other throughout the movement.', 'Strength', ['arms', 'grip']],
            ['Preacher Curl', 'Rest your arms on an angled pad and curl the bar upward, isolating the biceps.', 'Strength', ['arms', 'grip']],
            ['Tricep Pushdown', 'Using a cable, push the bar down until arms are fully extended, then control it back up.', 'Strength', ['arms', 'shoulder']],
            ['Skull Crusher', 'Lying on a bench, lower the bar toward your forehead by bending the elbows, then extend.', 'Strength', ['arms', 'shoulder']],
            ['Close-Grip Bench Press', 'Perform a bench press with hands set close together to emphasize the triceps.', 'Strength', ['arms', 'chest']],
            ['Leg Press', 'Push a weighted platform away using your legs from a seated, reclined position.', 'Strength', ['quads', 'glutes']],
            ['Leg Extension', 'Sitting, extend your knees against resistance until legs are straight, then lower.', 'Strength', ['quads', 'knee']],
            ['Leg Curl', 'Lying face down, curl your heels toward your glutes against resistance.', 'Strength', ['hamstrings', 'knee']],
            ['Hip Thrust', 'With shoulders on a bench and a bar over your hips, drive the hips upward.', 'Strength', ['glutes', 'hip']],
            ['Barbell Glute Bridge', 'Lying on the floor with a bar over your hips, drive through the heels to lift the hips.', 'Strength', ['glutes', 'lower back']],
            ['Good Morning', 'With the bar on your back, hinge forward at the hips keeping legs slightly bent, then return.', 'Strength', ['hamstrings', 'lower back']],
            ['Barbell Shrug', 'Hold the bar at hip height and shrug your shoulders straight up, then lower.', 'Strength', ['shoulder', 'grip']],
            ['Dumbbell Shrug', 'Hold dumbbells at your sides and shrug your shoulders straight up, then lower.', 'Strength', ['shoulder', 'grip']],
            ['Face Pull', 'Using a cable at head height, pull the rope toward your face, flaring the elbows out.', 'Strength', ['shoulder', 'back']],
            ['Lateral Raise', 'Raise dumbbells out to the sides until arms are parallel to the floor, then lower.', 'Strength', ['shoulder', 'arms']],
            ['Front Raise', 'Raise dumbbells straight in front of you to shoulder height, then lower.', 'Strength', ['shoulder', 'arms']],
            ['Rear Delt Fly', 'Bend forward and raise dumbbells out to the sides, squeezing the shoulder blades.', 'Strength', ['shoulder', 'back']],
            ['Upright Row', 'Pull the bar up along your body toward your chin, leading with the elbows.', 'Strength', ['shoulder', 'arms']],
            ['Cable Fly', 'Standing between cable towers, bring the handles together in front of your chest.', 'Strength', ['chest', 'shoulder']],
            ['Chest Fly', 'Lying on a bench, lower dumbbells out to the sides with a slight elbow bend, then bring them together.', 'Strength', ['chest', 'arms']],
            ['Clean and Jerk', 'Explosively pull the bar to your shoulders, then drive it overhead in one motion.', 'Strength', ['full body', 'power']],
            ['Snatch', 'In one explosive motion, pull the bar from the floor to overhead with arms locked out.', 'Strength', ['full body', 'power']],
            ['Power Clean', 'Explosively pull the bar from the floor to a front rack position on your shoulders.', 'Strength', ['full body', 'power']],
            ['Barbell Lunge', 'With the bar across your shoulders, step forward into a lunge and return to standing.', 'Strength', ['quads', 'glutes']],
            ['Goblet Squat', 'Hold a dumbbell close to your chest and squat down, keeping the chest upright.', 'Strength', ['quads', 'core']],
            ['Zercher Squat', 'Cradle the bar in the crooks of your elbows and squat down, keeping the torso upright.', 'Strength', ['core', 'quads']],
            ['Kettlebell Swing', 'Hinge at the hips and swing the kettlebell up to chest height using hip drive.', 'Strength', ['glutes', 'power']],
            ["Farmer's Carry", 'Hold a heavy weight in each hand and walk forward keeping the torso upright.', 'Strength', ['grip', 'full body']],
            ['Trap Bar Deadlift', 'Stand inside the trap bar and drive through the heels to stand tall, keeping the back flat.', 'Strength', ['back', 'glutes']],

            // Cardio
            ['Jumping Jacks', 'Jump while spreading legs and raising arms overhead, then return, at a steady pace.', 'Cardio', ['mobility', 'balance']],
            ['High Knees', 'Run in place driving knees up to hip height with a quick, rhythmic tempo.', 'Cardio', ['mobility', 'balance']],
            ['Jump Rope', 'Rotate a rope under your feet while hopping lightly at a steady rhythm.', 'Cardio', ['cardio', 'coordination']],
            ['Double Unders', 'Jump rope while passing the rope under your feet twice per jump.', 'Cardio', ['cardio', 'coordination']],
            ['Box Jump', 'Explosively jump onto a raised box, landing softly with bent knees.', 'Cardio', ['power', 'plyometric']],
            ['Butt Kicks', 'Jog in place while kicking your heels up toward your glutes.', 'Cardio', ['cardio', 'speed']],
            ['Skater Jumps', 'Leap laterally from one foot to the other in a skating motion.', 'Cardio', ['agility', 'balance']],
            ['Squat Jump', 'Perform a squat and explode upward into a jump, landing softly.', 'Cardio', ['power', 'quads']],
            ['Star Jump', 'Jump while spreading arms and legs into a star shape, then land softly.', 'Cardio', ['cardio', 'full body']],
            ['Shadow Boxing', 'Throw punches in the air at a steady pace while staying light on your feet.', 'Cardio', ['cardio', 'coordination']],
            ['Sprint Intervals', 'Alternate short bursts of maximum-speed running with periods of walking recovery.', 'Cardio', ['speed', 'endurance']],
            ['Stair Climbing', 'Climb stairs at a brisk, steady pace, driving through the legs.', 'Cardio', ['cardio', 'endurance']],
            ['Rowing Sprint', 'Row at maximum effort for a short, timed interval on a rowing machine.', 'Cardio', ['cardio', 'full body']],
            ['Elliptical Training', 'Maintain a steady stride on an elliptical machine, engaging arms and legs together.', 'Cardio', ['cardio', 'endurance']],
            ['Cycling Sprints', 'Pedal at maximum effort for short bursts, then recover at an easy pace.', 'Cardio', ['cardio', 'quads']],
            ['Battle Ropes', 'Grip heavy ropes and alternate slamming them in waves at a fast pace.', 'Cardio', ['full body', 'endurance']],
            ['Sled Push', 'Load a sled and drive it forward with powerful leg strides.', 'Cardio', ['full body', 'power']],
            ['Sled Pull', 'Attach a rope to a sled and pull it toward you hand over hand.', 'Cardio', ['back', 'grip']],
            ['Tuck Jump', 'Jump straight up and pull both knees toward your chest at the peak.', 'Cardio', ['power', 'plyometric']],
            ['Lateral Bounds', 'Leap side to side, landing softly on one leg each time.', 'Cardio', ['agility', 'balance']],
            ['Speed Skaters', 'Bound laterally from foot to foot in a quick, low skating motion.', 'Cardio', ['agility', 'cardio']],
            ['Side Shuffle', 'Shuffle sideways quickly while staying low, then reverse direction.', 'Cardio', ['agility', 'coordination']],
            ['Carioca Drill', 'Move sideways crossing one foot over and behind the other in a quick rhythm.', 'Cardio', ['agility', 'coordination']],
            ['Fast Feet Drill', 'Rapidly tap your feet in place, staying light and quick.', 'Cardio', ['speed', 'coordination']],
            ['Jump Lunges', 'Alternate lunges with an explosive jump switch between legs.', 'Cardio', ['power', 'quads']],
            ['Plyo Push-Up', 'Perform a push-up explosively enough for your hands to leave the floor.', 'Cardio', ['power', 'chest']],
            ['Standing Long Jump', 'From standing, swing your arms and jump forward as far as possible, landing softly.', 'Cardio', ['power', 'quads']],
            ['Treadmill Sprint', 'Run at maximum effort on a treadmill for a short, timed interval.', 'Cardio', ['speed', 'endurance']],
            ['Uphill Sprint', 'Sprint up an incline at maximum effort, driving the knees high.', 'Cardio', ['speed', 'quads']],
            ['Air Bike Sprint', 'Pedal an air bike at maximum effort, driving with both arms and legs.', 'Cardio', ['cardio', 'full body']],
            ['Stair Sprint', 'Sprint up a flight of stairs as quickly as possible.', 'Cardio', ['speed', 'quads']],
            ['Hill Sprint', 'Sprint up a hill at maximum effort, then walk back down to recover.', 'Cardio', ['speed', 'endurance']],
            ['Agility Ladder Drill', 'Move quickly through a floor ladder using short, precise footwork patterns.', 'Cardio', ['agility', 'coordination']],
            ['Cone Drill', 'Sprint and change direction sharply around a series of cones.', 'Cardio', ['agility', 'speed']],
            ['Shuttle Run', 'Sprint between two points, touching the ground at each end before turning back.', 'Cardio', ['speed', 'agility']],
            ['Wall Ball', 'Squat down then explosively throw a medicine ball against a wall target.', 'Cardio', ['full body', 'power']],
            ['Medicine Ball Slam', 'Raise a medicine ball overhead and slam it to the ground as hard as possible.', 'Cardio', ['full body', 'power']],
            ['Boxing Combos', 'Throw combinations of punches on a bag or pads at a fast, controlled pace.', 'Cardio', ['cardio', 'coordination']],
            ['Basketball Suicide', 'Sprint to a series of lines on a court, touching each before returning to the start.', 'Cardio', ['speed', 'endurance']],
            ['Rope Climb', 'Climb a hanging rope hand over hand using your arms and legs.', 'Cardio', ['grip', 'full body']],
            ['Frog Jump', 'Squat down and leap forward explosively, landing softly in a squat.', 'Cardio', ['power', 'quads']],
            ['Bear Crawl Sprint', 'Move quickly on hands and feet with hips low, covering ground fast.', 'Cardio', ['full body', 'coordination']],
            ['Line Hops', 'Hop side to side or forward and back over a line on the floor.', 'Cardio', ['agility', 'calves']],
            ['Ski Erg Sprint', 'Pull the handles of a ski ergometer down explosively at maximum effort.', 'Cardio', ['full body', 'endurance']],
            ['Split Jump', 'Jump from a lunge position and switch legs mid-air, landing in a lunge again.', 'Cardio', ['power', 'agility']],
            ['Kettlebell Snatch Cardio', 'Explosively pull a kettlebell from between your legs to overhead in one motion, repeating fast.', 'Cardio', ['full body', 'power']],
            ['Broad Jump Series', 'Perform consecutive standing long jumps, resetting briefly between each.', 'Cardio', ['power', 'endurance']],
            ['Speed Rope', 'Turn a jump rope as fast as possible for short, timed bursts.', 'Cardio', ['speed', 'coordination']],
            ['High Knee Sprint', 'Sprint forward while driving the knees up high with each stride.', 'Cardio', ['speed', 'quads']],
            ['Explosive Skater Bound', 'Perform skater jumps with maximum lateral distance and a brief stick landing.', 'Cardio', ['power', 'agility']],
        ];

        foreach ($exercises as [$name, $description, $categoryName, $tagNames]) {
            $exercise = Exercise::firstOrCreate(
                ['name' => $name],
                [
                    'description' => $description,
                    'category_id' => $categories[$categoryName]->id,
                    'video_url' => null,
                ],
            );

            $exercise->tags()->syncWithoutDetaching(
                collect($tagNames)->map(fn (string $t) => $tags[$t]->id)->all(),
            );
        }
    }
}
